### ISSUE TITLE
Integrate with task runners and JS-files

### ISSUE THREAD

**Issue by AntonGrekov** [css-modules/postcss-modules#102]
I searched for almost one full day to find a solution how to keep my current developing stack: gulp + pug + native JS and retain css-modules modular feature.

In Readme.md method of rendering HTML for PUG/Jade is presented but that method using plain node.js JavaScript. So, it skips using all mighty task runners that i cannot afford to stop using. 

How do i integrate postcss-modules into my gulp-tasks ? 
And how do i apply json-classnames scheme to my JS files, for example if i have jquery code using same class-names

**Comment by outpunk** [comment]
@AntonGrekov hi, I have described seemingly exactly this case in this article: https://evilmartians.com/chronicles/postcss-modules-isolate-em-all
And here is the example repo https://github.com/outpunk/postcss-modules-example/blob/master/Gulpfile.babel.js

**Comment by AntonGrekov** [comment]
I have read this article prior to creating issue here. It greatly describes using gulp and how to create json maps for css class-names for .css and .html files. But with .ejs template language which is not PUG/JADE that i am using. Also from this article it is not clear how to change class-names in .js files in project. What if i have 'scripts/app.js' file that uses class-names from .html markup for different purposes(animation, some features, etc.) and i need to replace class-names inside app.js file as well. Nothing about it in article. 

Thanks for responding so fast :)

**Comment by outpunk** [comment]
You should read the docs for Pug, I believe, it's possible to do your tasks the same way as for EJS. 
For JS, you can add an additional building step or write a plugin for that. 

Both of these tasks are out of the scope of this postcss-modules.

**Comment by AntonGrekov** [comment]
What about js files? If i have a js file that is using css classname from *.html, how do i change classes to make it work correctly ?
