### ISSUE TITLE
Usage with TailwindCSS

### ISSUE THREAD

**Issue by brielov** [css-modules/postcss-modules#110]
I've set up a small `react` project using `parcel` with `postcss-modules` and, when built, postcss-modules hashes all tailwind classes making it unusable when doing something like `<button className="bg-indigo-500" />`.

The desired behaviour for my use case is to have all the tailwind classes untouched for global access and then scoped classes for imported modules like `import styles from './Button.css'` which uses `@apply` tailwind directive.

This is my current `.postcssrc` config file:

```json
{
  "modules": true,
  "plugins": {
    "tailwindcss": {},
    "postcss-preset-env": {
      "stage": 0
    },
    "postcss-modules": {
      "generateScopedName": "[sha1:hash:base64:5]",
    }
  }
}
```

**Comment by outpunk** [comment]
You can [pass a function](https://github.com/css-modules/postcss-modules#localsconvention) into the `localsConvetion` option to choose which classes you want to leave without mangling.

**Comment by flyon** [comment]
for anyone in the future coming across this, I didn't get this to work with `localsConvention` which as I understand it determines the style of the KEYS in your json file outputs.

Rather I got this to work by making sure tailwind is handled as a `global` with 
```
globalModulePaths: [/tailwind/],
```
