### ISSUE TITLE
Add option for not doing :local by default.

### ISSUE THREAD

**Issue by dzearing** [css-modules/postcss-modules#22]
In order to ramp up a repo to use local scoped classes, it would be nice to do it incrementally.

Right now, the "local-by-default" plugin is hardcoded in postcss-modules index file, meaning without manually updating every css file to be :global, it's difficult to do this for large projects.

It would be very helpful to have an option to not include that plugin, so that projects could be incremental about module support.

**Comment by outpunk** [comment]
@dzearing Published the new version. Sorry for keeping you waiting so long.

**Comment by dzearing** [comment]
Thank you!
