### ISSUE TITLE
Doesn't work with other postcss plugins?

### ISSUE THREAD

**Issue by soluml** [css-modules/postcss-modules#24]
I've been trying to add this plugin to a postcss build I've been playing with.  I've got it all setup and configured and the build works great with autoprefixer and cssnano.  When I add in postcss-modules, everything appears to run fine... but no files are generated and no errors are given.

Here's a gist of my [css.js build file](https://gist.github.com/soluml/c6be8110ad3b3fbca6010b703f044463#file-css-js-L31).  If I add `cssmodules` to the array on Line 31 it fails silently. If I remove it, it works fine.

Any ideas?  Does PostCSS-Modules work with other plugins?  Is it a sourcemap issue?

**Comment by outpunk** [comment]
Actually, it works https://github.com/outpunk/postcss-modules/blob/master/test/test.js#L38

**Comment by outpunk** [comment]
Have you tried to run the example without Sass? Just to ensure.

**Comment by soluml** [comment]
Sass didn't seem to have any effect, but I was able to get it working like so -> https://gist.github.com/soluml/4340906d5307c96b2eebc3a523f4721e

Have no idea why, but at least it's working now.

**Comment by outpunk** [comment]
Thank you for sharing the solution. I will take a deep look at the problem when I have more time.

**Comment by outpunk** [comment]
One more issue https://github.com/ben-eb/cssnano/issues/163#issuecomment-208147922

**Comment by tatjsn** [comment]
This fix should resolves the problem css-modules/css-modules-loader-core#119. The "real" causes inside default plugins of `css-modules-loader-core` were already fixed now.

**Comment by outpunk** [comment]
Thanks,  I will close the issue after css-modules/css-modules-loader-core#119

**Comment by outpunk** [comment]
Fixed in [3.0.0](https://github.com/css-modules/postcss-modules/blob/master/CHANGELOG.md#300)
