### ISSUE TITLE
Pug (Jade) better example

### ISSUE THREAD

**Issue by admdh** [css-modules/postcss-modules#34]
Is there better example with Pug(jade), actually how can i use postcss-modules with express, json will be generated but how can i add generated classes to pug?

**Comment by outpunk** [comment]
@admdh Here is the example for EJS, but it's the same for Pug. https://github.com/outpunk/postcss-modules-example/blob/master/Gulpfile.babel.js#L34. Please refer to the Pug's documentation.

**Comment by NicholasNC** [comment]
@iamfrntdv 

[postcss-modules-pug-example](https://github.com/NicholasNC/nicholasnc.github.com/tree/master/blogs/postcss-modules-pug-example)

This is a Pug example.

`gulp + postcss-modules + pug` to use Css Modules.

I hope that will help you.
