### ISSUE TITLE
Is the information in postcss-loader accurate regarding this plugin?

### ISSUE THREAD

**Issue by adam-beck** [css-modules/postcss-modules#35]
If you take a look at https://github.com/postcss/postcss-loader#integration-with-css-modules you will see it mentions

> ...or use postcss-modules plugin instead of css-loader.

However, [this answer on SO](http://stackoverflow.com/a/35030581/3236303) makes it seem that the plugin does not work this way. Am I way off base here? I'm unable to get this working by simply just using this plugin and removing the `css-loader`.

**Comment by outpunk** [comment]
This is not a replacement for css-loader. This is a companion for it to use css modules at the server side.

**Comment by adam-beck** [comment]
Yes it looks like the documentation was changed. The quote I mentioned seems to imply it *is* a replacement. Thanks for clarifying though.
