### ISSUE TITLE
can not work with nested css

### ISSUE THREAD

**Issue by haohcraft** [css-modules/postcss-modules#39]
For the case below, 

```
.title {
    position: relative;

    &-content {
        position: absolute;
    }
}

```

it can only generate `title` related className but `title-content`.
For setting, I put `postcss-modules` *after* `postcss-nesting` and `postcss-nested`

**Comment by outpunk** [comment]
It shouldn't. The PostCSS philosophy is the same with Unix: Do just one thing and do it well.

**Comment by sunny-g** [comment]
Not sure what the intended location in the list of `plugins` should be, but I was only able to get it to work by placing it after `postcss-nested`.
