### ISSUE TITLE
getJSON and generateScopedName does not work together

### ISSUE THREAD

**Issue by mtinner** [css-modules/postcss-modules#42]
I would like to prefix my class names with a constant name.  Therefor no JSON need to be exported.

```
.pipe(postcss([
   modules(
       {
         getJSON: ()=> {
            return;
         }
      }, {generateScopedName: `${data.PROD_CLASS_PREFIX}[local]`}
   ),
]))
```

This generates no JSON, but the classnames will random pre- or postfixed.

**Comment by Chaptykov** [comment]
It works for me. Try to use single argument for `modules`.

```js
.pipe(postcss([
   modules({
     getJSON: ()=> {},
     generateScopedName: `${data.PROD_CLASS_PREFIX}[local]`
  }),
]))
```

**Comment by outpunk** [comment]
@Chaptykov @mtinner Exactly, there is just one options object in the arguments
