### ISSUE TITLE
Should this plugin inline @imports?

### ISSUE THREAD

**Issue by cameron-martin** [css-modules/postcss-modules#46]
According to the CSS Modules documentation:

> All URLs (`url(...)`) and `@imports` are in module request format (`./xxx` and `../xxx` means relative, `xxx` and `xxx/yyy` means in modules folder, i. e. in `node_modules`).

I noticed that `postcss-modules` does not inline `@import` statements. Is this a bug, or should I be using [`postcss-import`](https://github.com/postcss/postcss-import) for this?

**Comment by alexisvincent** [comment]
@cameron-martin I'm pretty sure this is expected behavior :)

**Comment by outpunk** [comment]
@cameron-martin @alexisvincent Nope, it shouldn't. Because there is another plugin for this. You should use `postcss-import`.
