### ISSUE TITLE
Support: build time issue

### ISSUE THREAD

**Issue by ZeeCoder** [css-modules/postcss-modules#49]
This is more of a support question than an actual issue.

I wanted to adopt css modules, but without webpack, so I wanted to generate the json map to each file, which I could later use to reference the original classesnames.
Now, my original setup was to have a folder, in which there's only one main.less file, which includes everything else in the folder.
Only this main got compiled, which also imported dependencies (like bootstrap grid, variables, etc...)

In order to make css modules work, I need to run the compilation process for each file, and have the files @import their dependencies.
Then I would have the json for each file, and at the end I could just concatenate everything together.

Unfortunately as I suspected this significantly increased build times, from ~200ms to ~2s.

My question is whether there's a better solution to achieve the same?
Am I approaching the problem completely wrong?
Because as it is the impact on dev experience might be too great for me to adopt this otherwise great project. :/

**Comment by outpunk** [comment]
This is a real problem, thank you for the reporting it. I'll think how to make the processing faster. Unfortunately, I have no free time for one or two next months. So, the issue won't be resolved as fast as I would like it to be.

**Comment by ZeeCoder** [comment]
I see, thanks for responding!
I'll think about solutions in the meantime, but unless this is addressed I don't think the solution is viable yet.

Which is probably the reason I don't really hear about css-modules.
Even if I use it through webpack, the same thing would happen.

**Comment by ZeeCoder** [comment]
I have an idea, but I'm not sure it's compatible with the current architecture, or how easy would it be to add.
Could you check it out @outpunk , depending on your opinion I might decide to do a custom implementation instead.

I'll outline the idea using Gulp as an example.
Assume we have something like : `gulp.src('./css-modules/**/*')`.
Now after this, we could have a preprocessing call, which would just add a comment at the top of each css module, something like this: `/* === css-module: {"path": "/the/absolute/path/to/the/module.css"} === */`

After that, everything can be concatenated and then processed as normal by less/sass whatever.

So now we would have a big css file, with a separator for modules.
Now this plugin as it currently stands, just converts all classes, using the css file's hash.
However if it had these comments, it could instead calculate the hash from comment-to-comment to get the actual module's hash instead of the concatenated one's.

Then instead of a single json argument in getJson, we could receive an array of path/json pairs for further processing.

So in Gulp, it would look like this:

```js

gulp.src('./css-modules/**/*')
    .pipe(cssModulesPreprocess()) // or cssModulesAnnotate
    .pipe(concat('main.css'))
    .pipe(less())
    .pipe(postcss([
        cssModules({
            getStats: function (stats) {
                // `moduleStats` example:
                // [
                //     {
                //         path: 'css-modules/global/avatar.css',
                //         json: { /* some JSON */ }
                //     },
                //     {
                //         path: 'css-modules/home/custom-module.css',
                //         json: { /* some JSON */ }
                //     }
                //     /* etc */
                // ]
            }
        }),
        autoprefixer()
    ]))
    .pipe(gulp.dest('./web/js'));

```

The hashing could even be done in the preprocessing step, and added to the comment, so that later on it's already available, and you don't have to deal with getting the module string from comment-to-comment.
Rather, you could just read the annotation and apply it to all classes after that until it encounters a different annotation, signaling the beginning of the next module.

Thought?

**Comment by ZeeCoder** [comment]
nvm, I started working on a custom implementation instead

**Comment by niksy** [comment]
@ZeeCoder did you manage to solve this issue?

**Comment by ZeeCoder** [comment]
Honestly I don't remember what exactly I was trying to achieve, but I've moved on from this styling pattern to import styles on a per-component basis, which sort of goes around this problem.

I'm also not using css-modules as the projects I work on nowadays aren't that complicated in terms of styling that you'd need the unique classname guarantee css-modules gives you.

Just BEM in itself works for me tbh 🤷‍♂️

**Comment by niksy** [comment]
@ZeeCoder yeah, I’m currently in BEM/SUIT camp myself and it works great, but I’m looking for more isolated approach without too much headeches regarding tooling and methodology. I’m trying to settle on BEM/SUIT naming scheme with CSS Modules benefits.

**Comment by ZeeCoder** [comment]
Well once you start using css modules, you don't need to do BEM at all. Unfortunately I'm not able to comment on whether build time changed at all since. 🤷‍♂️
