### ISSUE TITLE
how can you get globals on the exported object?

### ISSUE THREAD

**Issue by faceyspacey** [css-modules/postcss-modules#50]
I don't see why globals can't be exported just like locals, thereby giving you a consistent API in your components, i.e. so you don't have to juggle between using keys on a `styles` object and className strings.

**Comment by outpunk** [comment]
Nice idea! Could you make a pull request?

**Comment by axyz** [comment]
@outpunk can you point us to what part of the code filters out globals? (not sure if it is in this repo or some css-modules nested dependencies).

This would be useful for my use case in https://github.com/utilitycss/atomic as I use the keys in the json to delete rules that are not exported (e.g. whole css files coming from ICSS imports and composes) (https://github.com/utilitycss/atomic/blob/master/src/postcss/remove-unused-electrons.ts)

I was thinking that I can parse the CSS and look for :global(.myClass) instances with a regexp and include them in the custom getJSON as "myClass": "myClass", but that sounds like a dirty solution and would be better to not remove them in the first place.

**Comment by outpunk** [comment]
I think I can take a look In a couple of days

**Comment by outpunk** [comment]
@axyz I didn't forgot about this one. It has just a low priority among other my tasks. Hope, will dig into it this or next week

**Comment by axyz** [comment]
@outpunk sure, let me know if it is something I can help with given a little guidance, it is not super urgent but I want to avoid to put workarounds in place if possible.

**Comment by axyz** [comment]
@outpunk any update on this?

**Comment by outpunk** [comment]
@axyz I'm afraid, I have to rewrite the lib a bit first to avoid using dependencies https://github.com/css-modules/css-modules-loader-core/pull/236#issuecomment-647912926

**Comment by axyz** [comment]
do you think is still realistic to have the feature relatively quickly if you go for copy pasting the dependencies for now? Just need to know in order to decide to go for an alternative solution in the meanwhile or not.

**Comment by outpunk** [comment]
Hope to get an answer in a couple of days. Working on the deps now https://github.com/css-modules/postcss-modules/pull/108

**Comment by outpunk** [comment]
@faceyspacey @axyz Released in 3.1.0 https://github.com/css-modules/postcss-modules#exporting-globals
