### ISSUE TITLE
Doubts in integrating it in other PostCSS plugins

### ISSUE THREAD

**Issue by yuchi** [css-modules/postcss-modules#51]
While developing [`postcss-color-mod`](https://github.com/yuchi/postcss-color-mod) as an experiment, I believe I have surfaced an issue in integrating css-modules and uniqueness in other PostCSS plugins.

In `postcss-color-mod` I had 2 different integration requirements:

1. I have some cases where I need to create unique names for CSS Custom Properties (aka Variables) so that they never collide;
2. make sure that naming follows the rules specified by the user for CSS Modules.

If you see [at this line](https://github.com/yuchi/postcss-color-mod/blob/39475e7f443e2aac1d8233f22803d4d691fb10f0/src/operation.js#L57) I’m accessing `Core.scope.generateScopedName` from `css-modules-loader-core`. But his looks brittle because it’s not documented (I copied it by your own usage in the CSS Modules PostCSS plugin) and in the future you could (rightfully!) remove it without notice.

What do you think?

**Comment by outpunk** [comment]
I think, it's better for you to not use CSS Modules core at all. You can use [webpack's `interpolatename `](https://github.com/webpack/loader-utils#interpolatename) instead. Just give your users an option to provide their own name generator.
