### ISSUE TITLE
postcss-modules v0.6.2 fails on node v6

### ISSUE THREAD

**Issue by andykant** [css-modules/postcss-modules#53]
I recently tried to upgrade `postcss-modules` to latest (v0.6.2) but encountered a problem building when running on node v6.9.4. Looks like the issue is that `Object.values` in `behaviours.js` wasn't added until node v7.0.0.

I rolled back to v0.5.2 and that works fine (for those that run into the same problem).

```
    ERROR in ./~/css-loader!./~/postcss-loader!./src/styles.css
    Module build failed: TypeError: Object.values is not a function
        at isValidBehaviour (/home/ubuntu/PROJECT/node_modules/postcss-modules/build/behaviours.js:34:17)
        at getDefaultScopeBehaviour (/home/ubuntu/PROJECT/node_modules/postcss-modules/build/index.js:36:63)
```

**Comment by outpunk** [comment]
Published, thank you.
