### ISSUE TITLE
using composes brings in every style/class definition

### ISSUE THREAD

**Issue by feijoa** [css-modules/postcss-modules#54]
if my _typography.css has 100 lines

and then I have a button.css file like so:

.h1{
 composes: largest from _typography.css;
}

why does the compiled stylesheet have all 100 lines from _typography.css
when I only needed it to compose 1 style?

am I using or misunderstanding how to use 'composes' correctly?

**Comment by outpunk** [comment]
This is the intended behaviour and CSS Modules behaves so everywhere.

**Comment by daniilshustov** [comment]
Am I missing something, but why it is considered an intended behaviour? Building CSS Modules using webpack with css-loader `modules` parameter set to `true` does not output duplicated rules from multiple composes.

Is it possible to get the same result with postcss-modules without using cssnano or similar tools for development builds?
