### ISSUE TITLE
Add support for postcss-simple-vars and postcss-mixins

### ISSUE THREAD

**Issue by outpunk** [css-modules/postcss-modules#6]

**Comment by tarikihm** [comment]
I think the correct approach would be to reprocess the composed css through whatever postcss runner (plugins+parser) the user is using `postcss-module`s in.

In my case, I use many more plugins than `postcss-simple-var` and `postcss-mixins` and wouldn't want to redeclare them. Furthermore, I use `postcss-comment` and if the files are not processed through the parser, they will fail with syntax errors.

**Comment by outpunk** [comment]
@tarikihm this issue not just about CSS but also about exporting values to JSON for other languages.
