### ISSUE TITLE
PostCSS 6 Support

### ISSUE THREAD

**Issue by wbyoung** [css-modules/postcss-modules#60]
I see that [PostCSS is still at 5.2.8](https://github.com/css-modules/postcss-modules/blob/23140546c77bcd098cd938221e31432ad3616809/package.json#L23) in the code… is there any effort under way to upgrade this to 6.0?

**Comment by outpunk** [comment]
Done

**Comment by wbyoung** [comment]
@outpunk awesome, thanks!
