### ISSUE TITLE
Allow glob composes

### ISSUE THREAD

**Issue by nwmcsween** [css-modules/postcss-modules#66]
This is a pretty big change and duplicates some work in postcss-easy-import (glob import). Maybe postcss-modules, postcss-import and postcss-easy-import should be merged (or based off one another) as postcss-modules is basically a class based `@import` with optional mapping to localized classes.

Consider
```
.title {
	composes: * from './prefix*.css';
}
```

**Comment by TrySound** [comment]
@nwmcsween There's different mechanism under the hood. They can't be just merged. Also your example has a lot of implicits which reduces mainainability of your modules. You can get large classname in browser which can look like inline styles.

**Comment by outpunk** [comment]
@nwmcsween PostCSS-modules is just a wrapper around CSS Modules core, so it won't introduce any syntax changes, sorry. Regarding the proposal, I agree with @TrySound.
