### ISSUE TITLE
@import and duplicate class names

### ISSUE THREAD

**Issue by jaap3** [css-modules/postcss-modules#67]
I'm using PostCSS to generate a bundle of multiple components. PostCSS-Modules seems like the ideal way to handle global naming conflicts, but I must be using it wrong:

Given this `in.css`:

```
@import './component/one.css';
@import './component/two.css';
```

Where `component/one.css` contains:

```
.Button {
  color: black;
}
```

And `component/two.css` contains:

```
.Button {
  color: white;
}
```

When I run PostCSS using this config:

```
module.exports = {
  plugins: [
    require('postcss-import')(),
    require('postcss-cssnext')(),
    require('postcss-modules')()
  ]
}
```

`postcss -c postcss.config.js in.css -o out.css`

The output file `out.css` contains:

```
._Button_ggt0u_1 {
  color: black;
}
._Button_ggt0u_1 {
  color: white;
}
```

and `in.css.json` contains:

```
{"Button":"_Button_ggt0u_1"}
```

What I expected was a distinct global classname for each individual definition of `.Button` and either a json file per import, or a maybe nested json file with the entries per import.

Am I doing it wrong?

**Comment by michael-ciniawsky** [comment]
@jaap3 The scope name are generated by filename, so if you `@import` the 'components' (contents) first `postcss-modules` sees _one_ component (file). Try by adding `postcss-modules` to `postcss-import` 

```js
require('postcss-import')({ plugins: [ require('postcss-modules')() ] }) 
```

**Comment by jaap3** [comment]
Thanks, I knew I was doing something wrong!
