### ISSUE TITLE
standalone vesion

### ISSUE THREAD

**Issue by nripendra** [css-modules/postcss-modules#69]
As of now it is pretty much tied to nodejs. Is it possible to extract `core` which is independent of nodejs or browser environment. Just give in string content and get back javascript object with the json and css contents. Goal being something similar to that of `babel-standalone`, which I was able to integrate into dotnet using js engine.

**Comment by TrySound** [comment]
@nripendra postcss-modules is written for node.js. All babel stuff too. So you can't run it independent of nodejs. It should be in your environment.

**Comment by nripendra** [comment]
@TrySound Thanks for the reply!
Will probably try to fork it someday to fit my requirement

**Comment by lovemyliwu** [comment]
Happy to let you know, @nripendra I just made it, see https://www.npmjs.com/package/postcss-modules-standalone
