### ISSUE TITLE
Webpack config

### ISSUE THREAD

**Issue by Geoff-Ford** [css-modules/postcss-modules#71]
Hi, I appreciate that a similar question has been asked more than once before but none of the previous responses seem to give a definitive answer.

I am trying to use postcss-modules in a react project which I bundle with webpack. Whilst there is of course a client app, I am also server side rendering the initial request. I cannot find an example anywhere that shows how to configure webpack to use this package in this context. The example project quoted in previous responses uses gulp but as I am trying to keep my build within webpack alone, I would rather not have to put a specific build step in gulp.

Is it possible to configure this package in webpack to handle building SSR response and if so, do you have an example how this can be done?

I have also seen [this](https://github.com/css-modules/postcss-modules/issues/19#issuecomment-195906443) but don't understand where this is supposed to go.

**Comment by marzelin** [comment]
Have you tried the default way of  using `css modules` with webpack which is setting `css-loader` `options.modules` to `true`?
```js
{
  loader: "css-loader",
  options: {
    importLoaders: 1,
    modules: true
  }
}
```

**Comment by Geoff-Ford** [comment]
Thanks for responding @marzelin
I did actually manage to get things working after a few more hours of trawling through examples.

**Comment by 0rvar** [comment]
How did you solve this, @Geoff-Ford ?
