### ISSUE TITLE
Synchronous support?

### ISSUE THREAD

**Issue by florian-bd** [css-modules/postcss-modules#74]
At the moment it's not possible to use this plugin in synchronous mode.
```` 
postcss([postcssModules()]).process(cssString).css;
````
Is there any plan to support it in the future?

**Comment by TrySound** [comment]
@florian-bd Postcss itself supports sync mode only for debug purpose, not production using. What is use case which can't handle asynchronously?

**Comment by florian-bd** [comment]
I am trying to use it in a babel plugin :)

**Comment by TrySound** [comment]
Are you trying to css-modules-in-js?

**Comment by florian-bd** [comment]
No sure what that is but yeah basically I want to inject my css in the js

**Comment by TrySound** [comment]
@florian-bd But there're so much production ready libs for this, why do not use them?

**Comment by florian-bd** [comment]
Everything I found is tied to webpack. I am writing a component library and I was trying to avoid to serve the css as separate files so that the client project doesn't have to handle this with a loader.
I guess I should use CSS in JS in my library instead.

**Comment by TrySound** [comment]
Sure. [emotion](https://github.com/emotion-js/emotion) is quite nice.

**Comment by florian-bd** [comment]
Thanks for your help

**Comment by wangking873** [comment]
https://www.npmjs.com/package/postcss-modules-sync

**Comment by nvh95** [comment]
I could run `postcss-modules` sync successfully using https://www.npmjs.com/package/postcss-modules-sync. However, the `README.md` is not up-to-date, so I attach my snippet here:

Install `postcss-modules-sync`
```bash
npm install postcss-modules-sync
```

Transform CSS Modules, code written in CommonJS
```js
const postcss = require('postcss');
const CSSModulesSync = require('postcss-modules-sync').default;
const cssSrc = `.cssModuleClass {
  color: green;
}`;

let exportedTokens = {};

const result = postcss(
  CSSModulesSync({
    getJSON: (tokens) => {
      exportedTokens = tokens;
    },
  }),
)
.process(cssSrc, { from: ${JSON.stringify(filename)} });

// We can access `css` output there
console.log(result.css);

// This is important
// Run ".sync()" to get the exported tokens, otherwise, it's is `undefined`
result.sync();
console.log(exportedTokens);
```
