### ISSUE TITLE
More predictable scopedNames

### ISSUE THREAD

**Issue by JorritPosthuma** [css-modules/postcss-modules#78]
To support hot reloading, would it be possible to change the generated scoped names to a more predictable format? This would also fix https://github.com/parcel-bundler/parcel/issues/644.

A possibility might be to change in https://github.com/css-modules/postcss-modules/blob/master/src/generateScopedName.js:

```javascript
const hash = (0, _stringHash2.default)(css).toString(36).substr(0, 5);
return `_${name}_${hash}_${lineNumber}`;
```
To
```javascript
const hash = (0, _stringHash2.default)(filename).toString(36).substr(0, 5);
return `_${name}_${hash}`;
```

This way, the generated names only based on the filename and the class name (which I guess should be enough?)

**Comment by hayeah** [comment]
the `generateScopedName` option already solves this problem. We can close this issue and go to https://github.com/parcel-bundler/parcel/issues/644 instead.

**Comment by JorritPosthuma** [comment]
Nice! Thanks 👍
