### ISSUE TITLE
How to work with child combinator?

### ISSUE THREAD

**Issue by newlifeyh** [css-modules/postcss-modules#86]
```css
.parent {
    :global > .child {
    }
}
```

I don't want .child to be mangled, because it's from a library.
Adding `:global` before `>` or after `>` doesn't work.

**Comment by marvinhagemeister** [comment]
This should do the trick:
```
.parent {
    > :global(.child) {
    }
}
```

**Comment by outpunk** [comment]
Yep, that's the correct solution
